name: Auto-Push Excel
on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
jobs:
  push_excel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Commit and push changes
        run: |
          git config --global user.email "bharatade7@gmail.com"
          git config --global user.name "GitHub Actions"
          git add rvnl_data2_feb3.xlsx
          git commit -m "Auto-update Excel file" || exit 0
          git git push https://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@github.com/BHarat8600/BHarat8600.git

